services:
  cm-cicada:
    container_name: cm-cicada
    restart: always
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    image: cm-cicada:${TAG:-latest}
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./conf/:/conf/:ro
      - ./_airflow:/_airflow:rw
      - ./CM-CICADA.db:/CM-CICADA.db:rw
    network_mode: "host"
