services:
  cm-cicada:
    container_name: cm-cicada
    restart: always
    image: cloudbaristaorg/cm-cicada:edge
    volumes:
      - ./_airflow:/_airflow:rw
      - ./_data:/root/.cm-cicada:rw
    network_mode: "host"
