services:
  cm-cicada:
    container_name: cm-cicada
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: cm-cicada:${TAG:-latest}
    volumes:
      - ./_airflow:/_airflow:rw
      - ./CM-CICADA.db:/CM-CICADA.db:rw
    network_mode: "host"
