definitions:
  github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Data:
    properties:
      description:
        type: string
      task_groups:
        items:
          $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskGroup'
        type: array
    required:
    - task_groups
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Options:
    properties:
      api_connection_id:
        type: string
      endpoint:
        type: string
      method:
        type: string
      request_body:
        type: string
    required:
    - api_connection_id
    - endpoint
    - method
    - request_body
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Params:
    properties:
      properties: {}
      required:
        items:
          type: string
        type: array
    required:
    - properties
    - required
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.ParmaOption:
    properties:
      params:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Params'
    required:
    - params
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Task:
    properties:
      dependencies:
        items:
          type: string
        type: array
      name:
        type: string
      options:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Options'
      task_component:
        type: string
    required:
    - name
    - options
    - task_component
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent:
    properties:
      created_at:
        type: string
      data:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskData'
      name:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    required:
    - data
    - name
    - uuid
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskData:
    properties:
      options:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Options'
      param_option:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.ParmaOption'
    required:
    - options
    - param_option
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskGroup:
    properties:
      description:
        type: string
      task_group_name:
        type: string
      tasks:
        items:
          $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Task'
        type: array
    required:
    - task_group_name
    - tasks
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow:
    properties:
      created_at:
        type: string
      data:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Data'
      name:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    required:
    - data
    - name
    - uuid
    type: object
  github_com_cloud-barista_cm-cicada_pkg_api_rest_model.WorkflowTemplate:
    properties:
      created_at:
        type: string
      data:
        $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Data'
      name:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    required:
    - data
    - name
    - uuid
    type: object
  pkg_api_rest_controller.SimpleMsg:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /cicada/readyz:
    get:
      consumes:
      - application/json
      description: Check Cicada is ready
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get ready state.
          schema:
            $ref: '#/definitions/pkg_api_rest_controller.SimpleMsg'
        "500":
          description: Failed to check ready state.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Check Ready
      tags:
      - '[Admin] System management'
  /task_component:
    get:
      consumes:
      - application/json
      description: Get a list of task component.
      parameters:
      - description: Page of the task component list.
        in: query
        name: page
        type: string
      - description: Row of the task component list.
        in: query
        name: row
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get a list of task component.
          schema:
            items:
              $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
            type: array
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to get a list of task component.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: List TaskComponent
      tags:
      - '[Task Component]'
    post:
      consumes:
      - application/json
      description: Register the task component.
      parameters:
      - description: task component of the node.
        in: body
        name: TaskComponent
        required: true
        schema:
          $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully register the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to register the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Create TaskComponent
      tags:
      - '[Task Component]'
  /task_component/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete the task component.
      parameters:
      - description: UUID of the task component.
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully delete the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to delete the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Delete TaskComponent
      tags:
      - '[Task Component]'
    get:
      consumes:
      - application/json
      description: Get the task component.
      parameters:
      - description: UUID of the TaskComponent
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to get the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Get TaskComponent
      tags:
      - '[Task Component]'
    put:
      consumes:
      - application/json
      description: Update the task component.
      parameters:
      - description: UUID of the TaskComponent
        in: path
        name: uuid
        required: true
        type: string
      - description: task component to modify.
        in: body
        name: TaskComponent
        required: true
        schema:
          $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully update the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.TaskComponent'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to update the task component
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Update TaskComponent
      tags:
      - '[Task Component]'
  /workflow:
    get:
      consumes:
      - application/json
      description: Get a workflow list.
      parameters:
      - description: Page of the connection information list.
        in: query
        name: page
        type: string
      - description: Row of the connection information list.
        in: query
        name: row
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get a workflow list.
          schema:
            items:
              $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
            type: array
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to get a workflow list.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: List Workflow
      tags:
      - '[Workflow]'
    post:
      consumes:
      - application/json
      description: Create a workflow.
      parameters:
      - description: Workflow content
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully create the workflow.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.WorkflowTemplate'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to create DAG.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Create Workflow
      tags:
      - '[Workflow]'
  /workflow/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete the workflow.
      parameters:
      - description: UUID of the workflow.
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully delete the workflow
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to delete the workflow
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Delete Workflow
      tags:
      - '[Workflow]'
    get:
      consumes:
      - application/json
      description: Get the workflow.
      parameters:
      - description: UUID of the workflow.
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get the workflow.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to get the workflow.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Get Workflow
      tags:
      - '[Workflow]'
    put:
      consumes:
      - application/json
      description: Update the workflow content.
      parameters:
      - description: UUID of the workflow.
        in: path
        name: uuid
        required: true
        type: string
      - description: Workflow to modify.
        in: body
        name: Workflow
        required: true
        schema:
          $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully update the workflow
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to update the workflow
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Update Workflow
      tags:
      - '[Workflow]'
  /workflow/run/{uuid}:
    post:
      consumes:
      - application/json
      description: Run the workflow.
      parameters:
      - description: UUID of the workflow.
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully run the workflow.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.Workflow'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to run the Workflow
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Run Workflow
      tags:
      - '[Workflow]'
  /workflow_template:
    get:
      consumes:
      - application/json
      description: Get a list of workflow template.
      parameters:
      - description: Page of the workflow template list.
        in: query
        name: page
        type: string
      - description: Row of the workflow template list.
        in: query
        name: row
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get a list of workflow template.
          schema:
            items:
              $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.WorkflowTemplate'
            type: array
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to get a list of workflow template.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: List WorkflowTemplate
      tags:
      - '[Workflow Template]'
  /workflow_template/{uuid}:
    get:
      consumes:
      - application/json
      description: Get the workflow template.
      parameters:
      - description: UUID of the WorkflowTemplate
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get the workflow template
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_model.WorkflowTemplate'
        "400":
          description: Sent bad request.
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
        "500":
          description: Failed to get the workflow template
          schema:
            $ref: '#/definitions/github_com_cloud-barista_cm-cicada_pkg_api_rest_common.ErrorResponse'
      summary: Get WorkflowTemplate
      tags:
      - '[Workflow Template]'
swagger: "2.0"
